library/aik099/PHPUnit/BrowserConfiguration/ApiBrowserConfiguration.php, tests/aik099/PHPUnit/BrowserConfiguration/ApiBrowserConfigurationTestCase.php, tests/aik099/PHPUnit/Fixture/ApiIntegrationFixture.php, tests/aik099/PHPUnit/Integration/DataProviderTest.php
I've also identified and fixed an issue, when event listener in test was using wrong priority and resulted in test to always fail.
Closes #18
=> Don't run SauceLabs tests, when no API credentials are specified

tests/aik099/PHPUnit/BrowserConfiguration/BrowserConfigurationFactoryTest.php
I've marked test with `@medium` annotation to indicate that it can take longer then 1 second to execute.
I suspect that this has something to do with Travis CI that this particular test fails to complete within 1 second.
Closes #37
=> Increase timeout for `testCreateBrowserConfiguration` test

.travis.yml, docs/configuration.rst, docs/examples/configuration/config_via_setup_method.php, docs/examples/getting-started/cloud_selenium_configs.php, docs/getting-started.rst, library/aik099/PHPUnit/APIClient/BrowserStackAPIClient.php, library/aik099/PHPUnit/APIClient/IAPIClient.php, library/aik099/PHPUnit/APIClient/SauceLabsAPIClient.php, library/aik099/PHPUnit/BrowserConfiguration/ApiBrowserConfiguration.php, library/aik099/PHPUnit/BrowserConfiguration/BrowserStackBrowserConfiguration.php, phpunit.xml.dist, tests/aik099/PHPUnit/BrowserConfiguration/ApiBrowserConfigurationTestCase.php, tests/aik099/PHPUnit/BrowserConfiguration/BrowserStackBrowserConfigurationTest.php, tests/aik099/PHPUnit/BrowserConfiguration/SauceLabsBrowserConfigurationTest.php, tests/aik099/PHPUnit/Fixture/ApiIntegrationFixture.php, tests/aik099/PHPUnit/Fixture/SetupEventFixture.php
Also:
- added "IAPIClient::getInfo" method for getting session-related data from SauceLabs/BrowserStack
- updated DocBlock of "IAPIClient::updateStatus" to indicate that in fact array is being returned instead of boolean
- the "ApiBrowserConfiguration::getAPIClient" method was made public to allow users interacting with SauceLabs/BrowserStack
- update default Windows version to "Windows 7" in BrowserStack browser configuration
Closes #8
=> Complete support for BrowserStack

.travis.yml, docs/getting-started.rst, library/aik099/PHPUnit/BrowserConfiguration/BrowserStackBrowserConfiguration.php, library/aik099/PHPUnit/BrowserConfiguration/SauceLabsBrowserConfiguration.php, tests/aik099/PHPUnit/BrowserConfiguration/ApiBrowserConfigurationTestCase.php, tests/aik099/PHPUnit/BrowserConfiguration/BrowserStackBrowserConfigurationTest.php, tests/aik099/PHPUnit/BrowserConfiguration/SauceLabsBrowserConfigurationTest.php
Enabling tunnel support automatically, when library is being used on Travis CI is incorrect, because tests using the library might be accessing public only resoures and we don't want to slow down the build by waiting for tunnel to open.
This is exactly the case with library's own tests (it's accessing only http://www.google.com).
=> Don't create tunnel for SauceLabs on Travis CI by default

.travis.yml
Recent update to PHPUnit caused HHVM builds, attempting to collect code coverage fail with following output:
```
atal error: Uncaught exception 'PHP_CodeCoverage_Exception' with message 'This driver requires Xdebug' in /home/travis/build/minkphp/phpunit-mink/vendor/phpunit/php-code-coverage/src/CodeCoverage/Driver/Xdebug.php:25
Stack trace:
#0 /home/travis/build/minkphp/phpunit-mink/vendor/phpunit/php-code-coverage/src/CodeCoverage.php(914): PHP_CodeCoverage_Driver_Xdebug->__construct()
#1 /home/travis/build/minkphp/phpunit-mink/vendor/phpunit/php-code-coverage/src/CodeCoverage.php(99): PHP_CodeCoverage->selectDriver()
#2 /home/travis/build/minkphp/phpunit-mink/vendor/phpunit/phpunit/src/TextUI/TestRunner.php(331): PHP_CodeCoverage->__construct()
#3 …
```
=> Don't collect code coverage on HHVM because it doesn't have xdebug

tests/aik099/PHPUnit/Integration/BrowserStackAwareTestCase.php, tests/aik099/PHPUnit/Integration/DataProviderTest.php, tests/aik099/PHPUnit/Integration/IsolatedSessionStrategyTest.php, tests/aik099/PHPUnit/Integration/SharedSessionStrategyTest.php
The integration tests using SauceLabs seems to be stuck at some point, when communicating with SauceLabs servers (see https://travis-ci.org/minkphp/minkphp/phpunit-mink/builds/86064193) and are dropped by php-invoker.
Let's try if using BrowserStack instead will solve that problem.
=> Use BrowserStack instead of SauceLabs for integration tests

tests/aik099/PHPUnit/Integration/DataProviderTest.php, tests/aik099/PHPUnit/Integration/IsolatedSessionStrategyTest.php, tests/aik099/PHPUnit/Integration/SauceLabsAwareTestCase.php, tests/aik099/PHPUnit/Integration/SharedSessionStrategyTest.php
Reverts minkphp/phpunit-mink#61
This made things even worse. Now none if BrowserStack tests pass due limitations on OpenSource account (no concurrent tests possible, but Travis does them).
=> Revert "Use BrowserStack instead of SauceLabs for integration tests"

phpunit.xml.dist, tests/aik099/PHPUnit/Integration/IsolatedSessionStrategyTest.php, tests/aik099/PHPUnit/Integration/SharedSessionStrategyTest.php
Right now fact, that PHP_Invoker checks how long test runs ends up badly for SauceLabs/BrowserStack tests, because they can't do what they are doing within 1 second.
The more granular settings for PHPUnit strictness are used now.
=> Don't check how long test runs

.travis.yml
Before this PR we're depending on `dev-master` version of coverage reporting library, which ended up in failed build, because library author decided to increase minimal required PHP version from 5.3 to 5.5, which in turn made all PHP 5.4 and below builds fail.
This PR changes dependency to stable version (1.0), where using PHP 5.3 is still a possibility.
=> Use stable version of coverage reporting library during the build

composer.json, composer.lock, library/PimpleCopy/Pimple/Container.php, library/PimpleCopy/Pimple/ServiceProviderInterface.php, library/aik099/PHPUnit/DIContainer.php, phpunit.xml.dist, tests/PimpleCopy/Pimple/Fixtures/Invokable.php, tests/PimpleCopy/Pimple/Fixtures/NonInvokable.php, tests/PimpleCopy/Pimple/Fixtures/PimpleServiceProvider.php, tests/PimpleCopy/Pimple/Fixtures/Service.php, tests/PimpleCopy/Pimple/PimpleServiceProviderInterfaceTest.php, tests/PimpleCopy/Pimple/PimpleTest.php
=> Remove dependency on Pimple

library/aik099/PHPUnit/MinkDriver/GoutteDriverFactory.php
This reflects the update on MinkExtension: Behat/MinkExtension#236
Guzzle 6 no longer expects a nested array for the default configuration.
=> Add compatibility with Guzzle 6

.travis.yml, CHANGELOG.md, library/aik099/PHPUnit/AbstractPHPUnitCompatibilityTestCase.php, library/aik099/PHPUnit/BrowserTestCase.php, library/aik099/PHPUnit/PHPUnitCompatibilityTestCase.php
This should solve issue #77 
* apply fix based on solution in minkphp/Mink#687
* use locally installed phpunit version in travis ci instead of phpunit version provided by travis 
* not quite sure about naming of new abstract class ```AbstractPHPUnitCompatibilityTestCase``` and method ```onNotSuccessfulTestCompatibilized```
If this gets merged #87 can be closed as well cause it references same issue.
=> Fix compatibility with PHPUnit 5+

.travis.yml
Builds on travis ci raises error with:
```
HHVM is no longer supported on Ubuntu Precise. Please consider using Trusty with `dist: trusty`.
```
For discussion about this PR see https://github.com/minkphp/phpunit-mink/pull/89#issuecomment-316062732
Solution is based on PR console-helpers/svn-buddy#112.
=> Fix failing HHVM builds

.travis.yml, tests/PimpleCopy/Pimple/PimpleTest.php, tests/aik099/PHPUnit/Integration/SuiteBuildingTest.php
- this is first PR for #93 (PHPUnit 6 compatiblity)
- composer update phpunit/phpunit --with-dependencies will result in
following version test matrix
PHP | PHPUNIT
------- | -------------
5.3|4.8
5.4|4.8
5.5|4.8
5.6|5.7
7.0|6.2*
7.1*|6.2*
*not yet implemented/supported
=> use PHPUnit for used PHP version

CHANGELOG.md, composer.json, composer.lock, library/aik099/PHPUnit/AbstractPHPUnitCompatibilityTestCase.php, library/aik099/PHPUnit/TestSuite/AbstractTestSuite.php, tests/PimpleCopy/Pimple/PimpleServiceProviderInterfaceTest.php, tests/PimpleCopy/Pimple/PimpleTest.php, tests/aik099/PHPUnit/ApplicationTest.php, tests/aik099/PHPUnit/Event/TestEventTest.php, tests/aik099/PHPUnit/Integration/ApiIntegrationTest.php, tests/aik099/PHPUnit/Integration/DIContainerTest.php, tests/aik099/PHPUnit/Integration/EventDispatchingTest.php, tests/aik099/PHPUnit/Integration/SuiteBuildingTest.php, tests/aik099/PHPUnit/MinkDriver/DriverFactoryRegistryTest.php, tests/aik099/PHPUnit/MinkDriver/DriverFactoryTest.php, tests/aik099/PHPUnit/RemoteCoverage/RemoteCoverageHelperTest.php, tests/aik099/PHPUnit/RemoteCoverage/RemoteUrlTest.php, tests/aik099/PHPUnit/Session/SessionFactoryTest.php, tests/aik099/PHPUnit/Session/SessionStrategyManagerTest.php, tests/aik099/PHPUnit/Session/SessionStrategyTestCase.php, tests/aik099/PHPUnit/TestCase/ApplicationAwareTestCase.php, tests/aik099/PHPUnit/TestCase/EventDispatcherAwareTestCase.php
This is related to #93 
Not all PHPUnit classes are used with namespace, following are missing and will be handled in PR for PHPUnit 6 compatibility:
* \PHPUnit_Framework_TestResult
* \PHPUnit_Framework_IncompleteTestError
* \PHPUnit_Framework_SkippedTestError
* \PHPUnit_Framework_TestSuite_DataProvider
=> Bump PHPUnit version to 4.8.35+ or 5.4.3+ and use phpunit namespaces

.travis.yml, tests/aik099/PHPUnit/Integration/SuiteBuildingTest.php
1. confirms, that session strategy is set during test suite building
2. update Travis to fix PHP 5.3 build
3. update Travis to test on PHP 7.1
Related to #96
=> Confirm, that session strategy is correctly set during suite building

library/aik099/PHPUnit/TestSuite/AbstractTestSuite.php
Currently, a test case class with a single test contains ~300 public methods. The 2/3 of them are static methods (likely related to assertions).
Excluding these static public methods from the test suite building should speed up things.
=> Exclude assertion methods during the test suite building

tests/aik099/PHPUnit/BrowserConfiguration/BrowserConfigurationTest.php, tests/aik099/PHPUnit/BrowserTestCaseTest.php
In PHPUnit 10 the test name is a mandatory constructor argument. This PR prepares for PHPUnit 10 upgrade.
=> Specify test name for manually created TestCase objects

library/aik099/PHPUnit/BrowserTestCase.php, tests/aik099/PHPUnit/BrowserTestCaseTest.php, tests/aik099/PHPUnit/Fixture/ApiIntegrationFixture.php, tests/aik099/PHPUnit/Integration/BrowserStackAwareTestCase.php
=> Don't enable remote code coverage without a collection URL

CHANGELOG.md, library/aik099/PHPUnit/BrowserTestCase.php, tests/aik099/PHPUnit/BrowserTestCaseTest.php, tests/aik099/PHPUnit/Integration/SuiteBuildingTest.php
* Some of the `BrowserTestCase` class methods were publicly accessible only for testing purposes. Now these methods have `protected` visibility.
* Some of the `BrowserTestCase` properties, that were not supposed to be directly accessed by the class descendants had `protected` visibility. That is fixed now.
=> Reduce some "BrowserTestCase" class method visibility

CHANGELOG.md, docs/configuration.rst, docs/examples/configuration/per_test_case_browser_config.php, library/aik099/PHPUnit/Session/AbstractSessionStrategy.php, library/aik099/PHPUnit/Session/ISessionStrategy.php, library/aik099/PHPUnit/Session/IsolatedSessionStrategy.php, library/aik099/PHPUnit/Session/SharedSessionStrategy.php, tests/aik099/PHPUnit/Session/AbstractSessionStrategyTestCase.php, tests/aik099/PHPUnit/Session/IsolatedSessionStrategyTest.php, tests/aik099/PHPUnit/Session/SharedSessionStrategyTest.php
When dealing with shared session strategies it's hard to understand, whether the returned session was just created or was inherited from a previously executed test. This is not a problem now thanks to the `$this->getSessionStrategy()->isFreshSession()` code, that can be used anywhere during the test execution.
The practical use case for this functionality is to be able to perform login/logout once for all tests in the test case. Examples in the documentation were also updated to reflect this.
=> Ability to determine session freshness state

CHANGELOG.md, library/aik099/PHPUnit/TestSuite/AbstractTestSuite.php
The `BrowserTestCase::onTestSuiteEnded` event was also invoked for excluded tests. This happened because tests for iteration were retrieved from the `TestSuite::tests` method (which returns all tests and even those, that won't be executed).
Instead, interaction should be made through the `TestSuite` class object itself (as PHPUnit does). This has been fixed by this PR.
=> Invoke "BrowserTestCase::onTestSuiteEnded" method only for executed tests

library/aik099/PHPUnit/MinkDriver/AbstractDriverFactory.php, library/aik099/PHPUnit/MinkDriver/GoutteDriverFactory.php, library/aik099/PHPUnit/MinkDriver/IMinkDriverFactory.php, library/aik099/PHPUnit/MinkDriver/SahiDriverFactory.php, library/aik099/PHPUnit/MinkDriver/Selenium2DriverFactory.php, library/aik099/PHPUnit/MinkDriver/ZombieDriverFactory.php, tests/aik099/PHPUnit/MinkDriver/DriverFactoryTest.php
Changed error message formatting, that is shown, when driver package isn't installed.
```
Install MinkSelenium2Driver in order to use selenium2 driver.
```
```
The "selenium2" driver package is not installed. Please follow installation instructions at https://packagist.org/packages/behat/mink-selenium2-driver.
```
=> Simplify driver installation process

library/aik099/PHPUnit/MinkDriver/DriverFactoryRegistry.php, tests/aik099/PHPUnit/MinkDriver/DriverFactoryRegistryTest.php
When a developer have used a non-existing driver name, then inform him about possible valid driver names.
Before PR:
```
No driver factory for "unknown" driver.
```
After PR:
```
The "unknown" driver is unknown. Please instead use any of these supported drivers: "selenium2", "sahi", "goutte", "zombie".
```
=> Improve error, when unknown driver is being used

CHANGELOG.md, library/aik099/PHPUnit/Session/SharedSessionStrategy.php, tests/aik099/PHPUnit/Integration/SharedSessionStrategyTest.php, tests/aik099/PHPUnit/Session/SharedSessionStrategyTest.php
Now the popups, that test have opened are closed before starting the next test in the same test case class.
=> Closes popups after test finishes (shared strategy)

CHANGELOG.md, composer.json, composer.lock
Use the newer `console-helpers/phpunit-compat` library version to benefit from custom autoloader workflow (now library defines own autoloader for Composer to use instead of trying to include different class implementations based on IFs in a file composer autoloader includes).
=> Use newer "console-helpers/phpunit-compat" library version
